name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.0
        - name: Install Dependencies
          run: npm install
        - name: Execute Test Cases
          run: npx wdio wdio.conf.ts
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
